/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.ActionListener;

import javax.swing.Action;

/**
 *
 * @author rogercanayon
 */
public class TestVendFeatures extends javax.swing.JFrame {

    /**
     * Creates new form TestVendFeatures
     */
    public TestVendFeatures() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VendingFeaturesLbl = new javax.swing.JLabel();
        DoneBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SlotContainer = new javax.swing.JPanel();
        Slot1 = new javax.swing.JPanel();
        itemPicture1 = new javax.swing.JLabel();
        itemName1 = new javax.swing.JScrollPane();
        itemNameTextArea1 = new javax.swing.JTextArea();
        itemQuantity1 = new javax.swing.JLabel();
        availableLbl1 = new javax.swing.JLabel();
        itemCalories1 = new javax.swing.JLabel();
        priceLbl1 = new javax.swing.JLabel();
        itemPrice1 = new javax.swing.JLabel();
        PickSlot1 = new javax.swing.JButton();
        Slot2 = new javax.swing.JPanel();
        itemPicture2 = new javax.swing.JLabel();
        itemName2 = new javax.swing.JScrollPane();
        itemNameTextArea2 = new javax.swing.JTextArea();
        itemQuantity2 = new javax.swing.JLabel();
        availableLbl2 = new javax.swing.JLabel();
        itemCalories2 = new javax.swing.JLabel();
        priceLbl2 = new javax.swing.JLabel();
        itemPrice2 = new javax.swing.JLabel();
        PickSlot2 = new javax.swing.JButton();
        Slot3 = new javax.swing.JPanel();
        itemPicture3 = new javax.swing.JLabel();
        itemName3 = new javax.swing.JScrollPane();
        itemNameTextArea3 = new javax.swing.JTextArea();
        itemQuantity3 = new javax.swing.JLabel();
        availableLbl3 = new javax.swing.JLabel();
        itemCalories3 = new javax.swing.JLabel();
        priceLbl3 = new javax.swing.JLabel();
        itemPrice3 = new javax.swing.JLabel();
        PickSlot3 = new javax.swing.JButton();
        Slot4 = new javax.swing.JPanel();
        itemPicture4 = new javax.swing.JLabel();
        itemName4 = new javax.swing.JScrollPane();
        itemNameTextArea4 = new javax.swing.JTextArea();
        itemQuantity4 = new javax.swing.JLabel();
        availableLbl4 = new javax.swing.JLabel();
        itemCalories4 = new javax.swing.JLabel();
        priceLbl4 = new javax.swing.JLabel();
        itemPrice4 = new javax.swing.JLabel();
        PickSlot4 = new javax.swing.JButton();
        Slot5 = new javax.swing.JPanel();
        itemPicture5 = new javax.swing.JLabel();
        itemName5 = new javax.swing.JScrollPane();
        itemNameTextArea5 = new javax.swing.JTextArea();
        itemQuantity5 = new javax.swing.JLabel();
        availableLbl5 = new javax.swing.JLabel();
        itemCalories5 = new javax.swing.JLabel();
        priceLbl5 = new javax.swing.JLabel();
        itemPrice5 = new javax.swing.JLabel();
        PickSlot5 = new javax.swing.JButton();
        Slot6 = new javax.swing.JPanel();
        itemPicture6 = new javax.swing.JLabel();
        itemName6 = new javax.swing.JScrollPane();
        itemNameTextArea6 = new javax.swing.JTextArea();
        itemQuantity6 = new javax.swing.JLabel();
        availableLbl6 = new javax.swing.JLabel();
        itemCalories6 = new javax.swing.JLabel();
        priceLbl6 = new javax.swing.JLabel();
        itemPrice6 = new javax.swing.JLabel();
        PickSlot6 = new javax.swing.JButton();
        Slot7 = new javax.swing.JPanel();
        itemPicture7 = new javax.swing.JLabel();
        itemName7 = new javax.swing.JScrollPane();
        itemNameTextArea7 = new javax.swing.JTextArea();
        itemQuantity7 = new javax.swing.JLabel();
        availableLbl7 = new javax.swing.JLabel();
        itemCalories7 = new javax.swing.JLabel();
        priceLbl7 = new javax.swing.JLabel();
        itemPrice7 = new javax.swing.JLabel();
        PickSlot7 = new javax.swing.JButton();
        Slot8 = new javax.swing.JPanel();
        itemPicture8 = new javax.swing.JLabel();
        itemName8 = new javax.swing.JScrollPane();
        itemNameTextArea8 = new javax.swing.JTextArea();
        itemQuantity8 = new javax.swing.JLabel();
        availableLbl8 = new javax.swing.JLabel();
        itemCalories8 = new javax.swing.JLabel();
        priceLbl8 = new javax.swing.JLabel();
        itemPrice8 = new javax.swing.JLabel();
        PickSlot8 = new javax.swing.JButton();
        Slot9 = new javax.swing.JPanel();
        itemPicture9 = new javax.swing.JLabel();
        itemName9 = new javax.swing.JScrollPane();
        itemNameTextArea9 = new javax.swing.JTextArea();
        itemQuantity9 = new javax.swing.JLabel();
        availableLbl9 = new javax.swing.JLabel();
        itemCalories9 = new javax.swing.JLabel();
        priceLbl9 = new javax.swing.JLabel();
        itemPrice9 = new javax.swing.JLabel();
        PickSlot9 = new javax.swing.JButton();
        OrderDetailsField = new javax.swing.JScrollPane();
        OrderDetailsLbl = new javax.swing.JTextArea();
        MessageField = new javax.swing.JScrollPane();
        MessageFieldLbl = new javax.swing.JTextArea();
        PaymentPanel = new javax.swing.JPanel();
        DenominationComboBox = new javax.swing.JComboBox<>();
        DenominationLbl = new javax.swing.JLabel();
        InsertBtn = new javax.swing.JButton();
        YourItemLbl = new javax.swing.JLabel();
        ItemImageLbl = new javax.swing.JLabel();
        DispenseBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine Factory");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 88, 95));

        VendingFeaturesLbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        VendingFeaturesLbl.setForeground(new java.awt.Color(255, 255, 255));
        VendingFeaturesLbl.setText("Vending Features");

        DoneBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DoneBtn.setText("Done");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        SlotContainer.setBackground(new java.awt.Color(204, 204, 204));
        SlotContainer.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        itemPicture1.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName1.setBorder(null);

        itemNameTextArea1.setEditable(false);
        itemNameTextArea1.setColumns(7);
        itemNameTextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea1.setLineWrap(true);
        itemNameTextArea1.setRows(1);
        itemNameTextArea1.setText("Item Name");
        itemNameTextArea1.setWrapStyleWord(true);
        itemNameTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName1.setViewportView(itemNameTextArea1);

        itemQuantity1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity1.setText("0");
        itemQuantity1.setToolTipText("");

        availableLbl1.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl1.setText("Available:");

        itemCalories1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories1.setText("320 kCal");

        priceLbl1.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl1.setText("Price:");

        itemPrice1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice1.setText("0");
        itemPrice1.setToolTipText("");

        PickSlot1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot1.setText("PICK");

        javax.swing.GroupLayout Slot1Layout = new javax.swing.GroupLayout(Slot1);
        Slot1.setLayout(Slot1Layout);
        Slot1Layout.setHorizontalGroup(
            Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot1Layout.createSequentialGroup()
                        .addComponent(itemPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl1)
                                    .addComponent(itemQuantity1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot1Layout.createSequentialGroup()
                        .addGroup(Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot1Layout.createSequentialGroup()
                                .addComponent(itemCalories1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot1Layout.setVerticalGroup(
            Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot1Layout.createSequentialGroup()
                        .addComponent(priceLbl1)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice1)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl1)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories1))
                .addContainerGap())
        );

        SlotContainer.add(Slot1);

        itemPicture2.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName2.setBorder(null);

        itemNameTextArea2.setEditable(false);
        itemNameTextArea2.setColumns(7);
        itemNameTextArea2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea2.setLineWrap(true);
        itemNameTextArea2.setRows(1);
        itemNameTextArea2.setText("Item Name");
        itemNameTextArea2.setWrapStyleWord(true);
        itemNameTextArea2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName2.setViewportView(itemNameTextArea2);

        itemQuantity2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity2.setText("0");
        itemQuantity2.setToolTipText("");

        availableLbl2.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl2.setText("Available:");

        itemCalories2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories2.setText("320 kCal");

        priceLbl2.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl2.setText("Price:");

        itemPrice2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice2.setText("0");
        itemPrice2.setToolTipText("");

        PickSlot2.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot2.setText("PICK");

        javax.swing.GroupLayout Slot2Layout = new javax.swing.GroupLayout(Slot2);
        Slot2.setLayout(Slot2Layout);
        Slot2Layout.setHorizontalGroup(
            Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot2Layout.createSequentialGroup()
                        .addComponent(itemPicture2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl2)
                                    .addComponent(itemQuantity2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot2Layout.createSequentialGroup()
                        .addGroup(Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot2Layout.createSequentialGroup()
                                .addComponent(itemCalories2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot2Layout.setVerticalGroup(
            Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot2Layout.createSequentialGroup()
                        .addComponent(priceLbl2)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice2)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl2)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories2))
                .addContainerGap())
        );

        SlotContainer.add(Slot2);

        itemPicture3.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName3.setBorder(null);

        itemNameTextArea3.setEditable(false);
        itemNameTextArea3.setColumns(7);
        itemNameTextArea3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea3.setLineWrap(true);
        itemNameTextArea3.setRows(1);
        itemNameTextArea3.setText("Item Name");
        itemNameTextArea3.setWrapStyleWord(true);
        itemNameTextArea3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName3.setViewportView(itemNameTextArea3);

        itemQuantity3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity3.setText("0");
        itemQuantity3.setToolTipText("");

        availableLbl3.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl3.setText("Available:");

        itemCalories3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories3.setText("320 kCal");

        priceLbl3.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl3.setText("Price:");

        itemPrice3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice3.setText("0");
        itemPrice3.setToolTipText("");

        PickSlot3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot3.setText("PICK");

        javax.swing.GroupLayout Slot3Layout = new javax.swing.GroupLayout(Slot3);
        Slot3.setLayout(Slot3Layout);
        Slot3Layout.setHorizontalGroup(
            Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot3Layout.createSequentialGroup()
                        .addComponent(itemPicture3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl3)
                                    .addComponent(itemQuantity3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot3Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot3Layout.createSequentialGroup()
                        .addGroup(Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot3Layout.createSequentialGroup()
                                .addComponent(itemCalories3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot3Layout.setVerticalGroup(
            Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot3Layout.createSequentialGroup()
                        .addComponent(priceLbl3)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice3)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl3)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories3))
                .addContainerGap())
        );

        SlotContainer.add(Slot3);

        itemPicture4.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName4.setBorder(null);

        itemNameTextArea4.setEditable(false);
        itemNameTextArea4.setColumns(7);
        itemNameTextArea4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea4.setLineWrap(true);
        itemNameTextArea4.setRows(1);
        itemNameTextArea4.setText("Item Name");
        itemNameTextArea4.setWrapStyleWord(true);
        itemNameTextArea4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName4.setViewportView(itemNameTextArea4);

        itemQuantity4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity4.setText("0");
        itemQuantity4.setToolTipText("");

        availableLbl4.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl4.setText("Available:");

        itemCalories4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories4.setText("320 kCal");

        priceLbl4.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl4.setText("Price:");

        itemPrice4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice4.setText("0");
        itemPrice4.setToolTipText("");

        PickSlot4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot4.setText("PICK");

        javax.swing.GroupLayout Slot4Layout = new javax.swing.GroupLayout(Slot4);
        Slot4.setLayout(Slot4Layout);
        Slot4Layout.setHorizontalGroup(
            Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot4Layout.createSequentialGroup()
                        .addComponent(itemPicture4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl4)
                                    .addComponent(itemQuantity4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot4Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot4Layout.createSequentialGroup()
                        .addGroup(Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot4Layout.createSequentialGroup()
                                .addComponent(itemCalories4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot4Layout.setVerticalGroup(
            Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot4Layout.createSequentialGroup()
                        .addComponent(priceLbl4)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice4)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl4)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories4))
                .addContainerGap())
        );

        SlotContainer.add(Slot4);

        itemPicture5.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName5.setBorder(null);

        itemNameTextArea5.setEditable(false);
        itemNameTextArea5.setColumns(7);
        itemNameTextArea5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea5.setLineWrap(true);
        itemNameTextArea5.setRows(1);
        itemNameTextArea5.setText("Item Name");
        itemNameTextArea5.setWrapStyleWord(true);
        itemNameTextArea5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName5.setViewportView(itemNameTextArea5);

        itemQuantity5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity5.setText("0");
        itemQuantity5.setToolTipText("");

        availableLbl5.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl5.setText("Available:");

        itemCalories5.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories5.setText("320 kCal");

        priceLbl5.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl5.setText("Price:");

        itemPrice5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice5.setText("0");
        itemPrice5.setToolTipText("");

        PickSlot5.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot5.setText("PICK");

        javax.swing.GroupLayout Slot5Layout = new javax.swing.GroupLayout(Slot5);
        Slot5.setLayout(Slot5Layout);
        Slot5Layout.setHorizontalGroup(
            Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot5Layout.createSequentialGroup()
                        .addComponent(itemPicture5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl5)
                                    .addComponent(itemQuantity5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot5Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot5Layout.createSequentialGroup()
                        .addGroup(Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot5Layout.createSequentialGroup()
                                .addComponent(itemCalories5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot5Layout.setVerticalGroup(
            Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot5Layout.createSequentialGroup()
                        .addComponent(priceLbl5)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice5)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl5)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories5))
                .addContainerGap())
        );

        SlotContainer.add(Slot5);

        itemPicture6.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName6.setBorder(null);

        itemNameTextArea6.setEditable(false);
        itemNameTextArea6.setColumns(7);
        itemNameTextArea6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea6.setLineWrap(true);
        itemNameTextArea6.setRows(1);
        itemNameTextArea6.setText("Item Name");
        itemNameTextArea6.setWrapStyleWord(true);
        itemNameTextArea6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName6.setViewportView(itemNameTextArea6);

        itemQuantity6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity6.setText("0");
        itemQuantity6.setToolTipText("");

        availableLbl6.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl6.setText("Available:");

        itemCalories6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories6.setText("320 kCal");

        priceLbl6.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl6.setText("Price:");

        itemPrice6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice6.setText("0");
        itemPrice6.setToolTipText("");

        PickSlot6.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot6.setText("PICK");

        javax.swing.GroupLayout Slot6Layout = new javax.swing.GroupLayout(Slot6);
        Slot6.setLayout(Slot6Layout);
        Slot6Layout.setHorizontalGroup(
            Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot6Layout.createSequentialGroup()
                        .addComponent(itemPicture6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl6)
                                    .addComponent(itemQuantity6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot6Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot6Layout.createSequentialGroup()
                        .addGroup(Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot6Layout.createSequentialGroup()
                                .addComponent(itemCalories6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot6Layout.setVerticalGroup(
            Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot6Layout.createSequentialGroup()
                        .addComponent(priceLbl6)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice6)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl6)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories6))
                .addContainerGap())
        );

        SlotContainer.add(Slot6);

        itemPicture7.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName7.setBorder(null);

        itemNameTextArea7.setEditable(false);
        itemNameTextArea7.setColumns(7);
        itemNameTextArea7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea7.setLineWrap(true);
        itemNameTextArea7.setRows(1);
        itemNameTextArea7.setText("Item Name");
        itemNameTextArea7.setWrapStyleWord(true);
        itemNameTextArea7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName7.setViewportView(itemNameTextArea7);

        itemQuantity7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity7.setText("0");
        itemQuantity7.setToolTipText("");

        availableLbl7.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl7.setText("Available:");

        itemCalories7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories7.setText("320 kCal");

        priceLbl7.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl7.setText("Price:");

        itemPrice7.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice7.setText("0");
        itemPrice7.setToolTipText("");

        PickSlot7.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot7.setText("PICK");

        javax.swing.GroupLayout Slot7Layout = new javax.swing.GroupLayout(Slot7);
        Slot7.setLayout(Slot7Layout);
        Slot7Layout.setHorizontalGroup(
            Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot7Layout.createSequentialGroup()
                        .addComponent(itemPicture7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot7Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl7)
                                    .addComponent(itemQuantity7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot7Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot7Layout.createSequentialGroup()
                        .addGroup(Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName7, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot7Layout.createSequentialGroup()
                                .addComponent(itemCalories7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot7Layout.setVerticalGroup(
            Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot7Layout.createSequentialGroup()
                        .addComponent(priceLbl7)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice7)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl7)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories7))
                .addContainerGap())
        );

        SlotContainer.add(Slot7);

        itemPicture8.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName8.setBorder(null);

        itemNameTextArea8.setEditable(false);
        itemNameTextArea8.setColumns(7);
        itemNameTextArea8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea8.setLineWrap(true);
        itemNameTextArea8.setRows(1);
        itemNameTextArea8.setText("Item Name");
        itemNameTextArea8.setWrapStyleWord(true);
        itemNameTextArea8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName8.setViewportView(itemNameTextArea8);

        itemQuantity8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity8.setText("0");
        itemQuantity8.setToolTipText("");

        availableLbl8.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl8.setText("Available:");

        itemCalories8.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories8.setText("320 kCal");

        priceLbl8.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl8.setText("Price:");

        itemPrice8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice8.setText("0");
        itemPrice8.setToolTipText("");

        PickSlot8.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot8.setText("PICK");

        javax.swing.GroupLayout Slot8Layout = new javax.swing.GroupLayout(Slot8);
        Slot8.setLayout(Slot8Layout);
        Slot8Layout.setHorizontalGroup(
            Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot8Layout.createSequentialGroup()
                        .addComponent(itemPicture8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl8)
                                    .addComponent(itemQuantity8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot8Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot8Layout.createSequentialGroup()
                        .addGroup(Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName8, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot8Layout.createSequentialGroup()
                                .addComponent(itemCalories8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot8Layout.setVerticalGroup(
            Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot8Layout.createSequentialGroup()
                        .addComponent(priceLbl8)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice8)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl8)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories8))
                .addContainerGap())
        );

        SlotContainer.add(Slot8);

        itemPicture9.setBackground(new java.awt.Color(102, 102, 102));
        itemPicture9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemPicture9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N

        itemName9.setBorder(null);

        itemNameTextArea9.setEditable(false);
        itemNameTextArea9.setColumns(7);
        itemNameTextArea9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        itemNameTextArea9.setLineWrap(true);
        itemNameTextArea9.setRows(1);
        itemNameTextArea9.setText("Item Name");
        itemNameTextArea9.setWrapStyleWord(true);
        itemNameTextArea9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemName9.setViewportView(itemNameTextArea9);

        itemQuantity9.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemQuantity9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemQuantity9.setText("0");
        itemQuantity9.setToolTipText("");

        availableLbl9.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        availableLbl9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        availableLbl9.setText("Available:");

        itemCalories9.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        itemCalories9.setText("320 kCal");

        priceLbl9.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        priceLbl9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        priceLbl9.setText("Price:");

        itemPrice9.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        itemPrice9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        itemPrice9.setText("0");
        itemPrice9.setToolTipText("");

        PickSlot9.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        PickSlot9.setText("PICK");

        javax.swing.GroupLayout Slot9Layout = new javax.swing.GroupLayout(Slot9);
        Slot9.setLayout(Slot9Layout);
        Slot9Layout.setHorizontalGroup(
            Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Slot9Layout.createSequentialGroup()
                        .addComponent(itemPicture9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Slot9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableLbl9)
                                    .addComponent(itemQuantity9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(itemPrice9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Slot9Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(priceLbl9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Slot9Layout.createSequentialGroup()
                        .addGroup(Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemName9, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Slot9Layout.createSequentialGroup()
                                .addComponent(itemCalories9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PickSlot9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        Slot9Layout.setVerticalGroup(
            Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Slot9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(itemPicture9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Slot9Layout.createSequentialGroup()
                        .addComponent(priceLbl9)
                        .addGap(2, 2, 2)
                        .addComponent(itemPrice9)
                        .addGap(6, 6, 6)
                        .addComponent(availableLbl9)
                        .addGap(2, 2, 2)
                        .addComponent(itemQuantity9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemName9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PickSlot9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemCalories9))
                .addContainerGap())
        );

        SlotContainer.add(Slot9);

        jPanel2.add(SlotContainer);
        SlotContainer.setBounds(0, 0, 370, 430);

        OrderDetailsLbl.setEditable(false);
        OrderDetailsLbl.setColumns(10);
        OrderDetailsLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        OrderDetailsLbl.setLineWrap(true);
        OrderDetailsLbl.setRows(3);
        OrderDetailsLbl.setText("Please pick an item.");
        OrderDetailsLbl.setWrapStyleWord(true);
        OrderDetailsField.setViewportView(OrderDetailsLbl);

        jPanel2.add(OrderDetailsField);
        OrderDetailsField.setBounds(380, 10, 160, 70);

        MessageFieldLbl.setEditable(false);
        MessageFieldLbl.setColumns(8);
        MessageFieldLbl.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        MessageFieldLbl.setLineWrap(true);
        MessageFieldLbl.setRows(4);
        MessageFieldLbl.setWrapStyleWord(true);
        MessageField.setViewportView(MessageFieldLbl);

        jPanel2.add(MessageField);
        MessageField.setBounds(380, 90, 160, 90);

        PaymentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Payment"));

        DenominationLbl.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DenominationLbl.setText("Denomination");

        InsertBtn.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        InsertBtn.setText("Insert");

        javax.swing.GroupLayout PaymentPanelLayout = new javax.swing.GroupLayout(PaymentPanel);
        PaymentPanel.setLayout(PaymentPanelLayout);
        PaymentPanelLayout.setHorizontalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DenominationComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PaymentPanelLayout.createSequentialGroup()
                        .addComponent(DenominationLbl)
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaymentPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(InsertBtn)))
                .addContainerGap())
        );
        PaymentPanelLayout.setVerticalGroup(
            PaymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaymentPanelLayout.createSequentialGroup()
                .addComponent(DenominationLbl)
                .addGap(4, 4, 4)
                .addComponent(DenominationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsertBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PaymentPanel);
        PaymentPanel.setBounds(380, 190, 160, 99);

        YourItemLbl.setText("Your item:");
        jPanel2.add(YourItemLbl);
        YourItemLbl.setBounds(380, 340, 120, 17);

        ItemImageLbl.setBackground(new java.awt.Color(0, 0, 0));
        ItemImageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Elements/ItemElements/hokkaido w_ pearls.png"))); // NOI18N
        ItemImageLbl.setText("jLabel3");
        jPanel2.add(ItemImageLbl);
        ItemImageLbl.setBounds(470, 340, 46, 46);

        DispenseBtn.setText("Dispense");
        jPanel2.add(DispenseBtn);
        DispenseBtn.setBounds(380, 300, 85, 23);

        CancelBtn.setText("Cancel");
        jPanel2.add(CancelBtn);
        CancelBtn.setBounds(470, 300, 70, 23);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VendingFeaturesLbl)
                        .addContainerGap(313, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(VendingFeaturesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoneBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDenomComboBoxValues(int[] denom)
    {
        DenominationComboBox.addItem("₱" + denom[0]);
        DenominationComboBox.addItem("₱" + denom[1]);
        DenominationComboBox.addItem("₱" + denom[2]);
        DenominationComboBox.addItem("₱" + denom[3]);
        DenominationComboBox.addItem("₱" + denom[4]);
        DenominationComboBox.addItem("₱" + denom[5]);
        DenominationComboBox.addItem("₱" + denom[6]);
        DenominationComboBox.addItem("₱" + denom[7]);
        DenominationComboBox.addItem("₱" + denom[8]);
        setDenomComboBoxSelectedIndex();
    }

    public void setDenomComboBoxSelectedIndex()
    {
        DenominationComboBox.setSelectedItem(null);
    }

    public int getSelectedDenom()
    {
        String getdenom = (String)DenominationComboBox.getSelectedItem();
        int denom = 0;
        try {
            denom = Integer.parseInt(getdenom.substring(1));
        } catch (Exception e) {
            
        }
        return denom;
    }

    // Button listeners
    public void setDoneBtnListener(ActionListener actn)
    {
        DoneBtn.addActionListener(actn);
    }
    
    public void setPickSlot1BtnListener(ActionListener actn)
    {
        PickSlot1.addActionListener(actn);
    }

    public void setPickSlot2BtnListener(ActionListener actn)
    {
        PickSlot2.addActionListener(actn);
    }
    
    public void setPickSlot3BtnListener(ActionListener actn)
    {
        PickSlot3.addActionListener(actn);
    }

    public void setPickSlot4BtnListener(ActionListener actn)
    {
        PickSlot4.addActionListener(actn);
    }

    public void setPickSlot5BtnListener(ActionListener actn)
    {
        PickSlot5.addActionListener(actn);
    }
    
    public void setPickSlot6BtnListener(ActionListener actn)
    {
        PickSlot6.addActionListener(actn);
    }

    public void setPickSlot7BtnListener(ActionListener actn)
    {
        PickSlot7.addActionListener(actn);
    }

    public void setPickSlot8BtnListener(ActionListener actn)
    {
        PickSlot8.addActionListener(actn);
    }
    
    public void setPickSlot9BtnListener(ActionListener actn)
    {
        PickSlot9.addActionListener(actn);
    }

    public void setInsertCashListener(ActionListener actn)
    {
        InsertBtn.addActionListener(actn);
    }

    public void setDispenseBtnListener(ActionListener actn)
    {
        DispenseBtn.addActionListener(actn);
    }

    public void setCancelBtnListener(ActionListener actn)
    {
        CancelBtn.addActionListener(actn);
    }

    // Button enable

    public void setCancelBtnEnable(boolean check)
    {
        CancelBtn.setEnabled(check);
    }

    public void setInsertCashEnable(boolean check)
    {
        InsertBtn.setEnabled(check);
    }

    public void setDispenseBtnEnable(boolean check)
    {
        DispenseBtn.setEnabled(check);
    }

    public void setPickSlot1Enable(boolean check)
    {
        PickSlot1.setEnabled(check);
    }

    public void setPickSlot2Enable(boolean check)
    {
        PickSlot2.setEnabled(check);
    }

    public void setPickSlot3Enable(boolean check)
    {
        PickSlot3.setEnabled(check);
    }

    public void setPickSlot4Enable(boolean check)
    {
        PickSlot4.setEnabled(check);
    }

    public void setPickSlot5Enable(boolean check)
    {
        PickSlot5.setEnabled(check);
    }

    public void setPickSlot6Enable(boolean check)
    {
        PickSlot6.setEnabled(check);
    }

    public void setPickSlot7Enable(boolean check)
    {
        PickSlot7.setEnabled(check);
    }

    public void setPickSlot8Enable(boolean check)
    {
        PickSlot8.setEnabled(check);
    }

    public void setPickSlot9Enable(boolean check)
    {
        PickSlot9.setEnabled(check);
    }


    // Set item names in GUI

    public void setItemName1(String name)
    {
        this.itemNameTextArea1.setText(name);
    }

    public void setItemName2(String name)
    {
        this.itemNameTextArea2.setText(name);
    }

    public void setItemName3(String name)
    {
        this.itemNameTextArea3.setText(name);
    }

    public void setItemName4(String name)
    {
        this.itemNameTextArea4.setText(name);
    }

    public void setItemName5(String name)
    {
        this.itemNameTextArea5.setText(name);
    }

    public void setItemName6(String name)
    {
        this.itemNameTextArea6.setText(name);
    }

    public void setItemName7(String name)
    {
        this.itemNameTextArea7.setText(name);
    }

    public void setItemName8(String name)
    {
        this.itemNameTextArea8.setText(name);
    }

    public void setItemName9(String name)
    {
        this.itemNameTextArea9.setText(name);
    }


    // Setting calories


    public void setItemCalories1(int calories)
    {
        this.itemCalories1.setText(calories + " kCal");
    }

    public void setItemCalories2(int calories)
    {
        this.itemCalories2.setText(calories + " kCal");
    }

    public void setItemCalories3(int calories)
    {
        this.itemCalories3.setText(calories + " kCal");
    }

    public void setItemCalories4(int calories)
    {
        this.itemCalories4.setText(calories + " kCal");
    }

    public void setItemCalories5(int calories)
    {
        this.itemCalories5.setText(calories + " kCal");
    }

    public void setItemCalories6(int calories)
    {
        this.itemCalories6.setText(calories + " kCal");
    }

    public void setItemCalories7(int calories)
    {
        this.itemCalories7.setText(calories + " kCal");
    }

    public void setItemCalories8(int calories)
    {
        this.itemCalories8.setText(calories + " kCal");
    }

    public void setItemCalories9(int calories)
    {
        this.itemCalories9.setText(calories + " kCal");
    }
    
    // Setting price

    public void setItemPrice1(int price)
    {
        this.itemPrice1.setText("₱" + price);
    }

    public void setItemPrice2(int price)
    {
        this.itemPrice2.setText("₱" + price);
    }

    public void setItemPrice3(int price)
    {
        this.itemPrice3.setText("₱" + price);
    }

    public void setItemPrice4(int price)
    {
        this.itemPrice4.setText("₱" + price);
    }

    public void setItemPrice5(int price)
    {
        this.itemPrice5.setText("₱" + price);
    }

    public void setItemPrice6(int price)
    {
        this.itemPrice6.setText("₱" + price);
    }

    public void setItemPrice7(int price)
    {
        this.itemPrice7.setText("₱" + price);
    }

    public void setItemPrice8(int price)
    {
        this.itemPrice8.setText("₱" + price);
    }

    public void setItemPrice9(int price)
    {
        this.itemPrice9.setText("₱" + price);
    }

    // Setting the quantity available

    public void setItemQuantity1(int quantity)
    {
        this.itemQuantity1.setText(String.valueOf(quantity));
    }

    public void setItemQuantity2(int quantity)
    {
        this.itemQuantity2.setText(String.valueOf(quantity));
    }

    public void setItemQuantity3(int quantity)
    {
        this.itemQuantity3.setText(String.valueOf(quantity));
    }

    public void setItemQuantity4(int quantity)
    {
        this.itemQuantity4.setText(String.valueOf(quantity));
    }

    public void setItemQuantity5(int quantity)
    {
        this.itemQuantity5.setText(String.valueOf(quantity));
    }

    public void setItemQuantity6(int quantity)
    {
        this.itemQuantity6.setText(String.valueOf(quantity));
    }

    public void setItemQuantity7(int quantity)
    {
        this.itemQuantity7.setText(String.valueOf(quantity));
    }

    public void setItemQuantity8(int quantity)
    {
        this.itemQuantity8.setText(String.valueOf(quantity));
    }

    public void setItemQuantity9(int quantity)
    {
        this.itemQuantity9.setText(String.valueOf(quantity));
    }

    // Setting picture

    public void setItemPicture1(String path)
    {
        itemPicture1.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture2(String path)
    {
        itemPicture2.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture3(String path)
    {
        itemPicture3.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture4(String path)
    {
        itemPicture4.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture5(String path)
    {
        itemPicture5.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture6(String path)
    {
        itemPicture6.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture7(String path)
    {
        itemPicture7.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture8(String path)
    {
        itemPicture8.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    public void setItemPicture9(String path)
    {
        itemPicture9.setIcon(new javax.swing.ImageIcon(getClass().getResource(path)));
    }

    // Set text areas

    public void restartOrderDetailsLbl()
    {
        OrderDetailsLbl.setText("Please pick an item.");
    }

    public void setOrderDetailsLbl(String order)
    {
        OrderDetailsLbl.setText("Order:\n" + order);
    }

    public void setFlavorDetailsLbl(String order)
    {
        String currentText = OrderDetailsLbl.getText();
        OrderDetailsLbl.setText(currentText + "\nFlavor: " + order);
    }

    public void setSinkerDetailsLbl(String order)
    {
        String currentText = OrderDetailsLbl.getText();
        OrderDetailsLbl.setText(currentText + "\nSinker: " + order);
    }

    // sets the text of message lbl to the string provided.
    public void setMessageLbl(String output)
    {
        MessageFieldLbl.setText(output);
    }

    // adds the string provided to the existing info in messagelbl
    public void addInfoInMessageLbl(String additionalInfo)
    {
        String currentText = MessageFieldLbl.getText();
        MessageFieldLbl.setText(currentText + "\n" + additionalInfo);
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestVendFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestVendFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestVendFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestVendFeatures.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestVendFeatures().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JComboBox<String> DenominationComboBox;
    private javax.swing.JLabel DenominationLbl;
    private javax.swing.JButton DispenseBtn;
    private javax.swing.JButton DoneBtn;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JLabel ItemImageLbl;
    private javax.swing.JScrollPane MessageField;
    private javax.swing.JTextArea MessageFieldLbl;
    private javax.swing.JScrollPane OrderDetailsField;
    private javax.swing.JTextArea OrderDetailsLbl;
    private javax.swing.JPanel PaymentPanel;
    private javax.swing.JButton PickSlot1;
    private javax.swing.JButton PickSlot2;
    private javax.swing.JButton PickSlot3;
    private javax.swing.JButton PickSlot4;
    private javax.swing.JButton PickSlot5;
    private javax.swing.JButton PickSlot6;
    private javax.swing.JButton PickSlot7;
    private javax.swing.JButton PickSlot8;
    private javax.swing.JButton PickSlot9;
    private javax.swing.JPanel Slot1;
    private javax.swing.JPanel Slot2;
    private javax.swing.JPanel Slot3;
    private javax.swing.JPanel Slot4;
    private javax.swing.JPanel Slot5;
    private javax.swing.JPanel Slot6;
    private javax.swing.JPanel Slot7;
    private javax.swing.JPanel Slot8;
    private javax.swing.JPanel Slot9;
    private javax.swing.JPanel SlotContainer;
    private javax.swing.JLabel VendingFeaturesLbl;
    private javax.swing.JLabel YourItemLbl;
    private javax.swing.JLabel availableLbl1;
    private javax.swing.JLabel availableLbl2;
    private javax.swing.JLabel availableLbl3;
    private javax.swing.JLabel availableLbl4;
    private javax.swing.JLabel availableLbl5;
    private javax.swing.JLabel availableLbl6;
    private javax.swing.JLabel availableLbl7;
    private javax.swing.JLabel availableLbl8;
    private javax.swing.JLabel availableLbl9;
    private javax.swing.JLabel itemCalories1;
    private javax.swing.JLabel itemCalories2;
    private javax.swing.JLabel itemCalories3;
    private javax.swing.JLabel itemCalories4;
    private javax.swing.JLabel itemCalories5;
    private javax.swing.JLabel itemCalories6;
    private javax.swing.JLabel itemCalories7;
    private javax.swing.JLabel itemCalories8;
    private javax.swing.JLabel itemCalories9;
    private javax.swing.JScrollPane itemName1;
    private javax.swing.JScrollPane itemName2;
    private javax.swing.JScrollPane itemName3;
    private javax.swing.JScrollPane itemName4;
    private javax.swing.JScrollPane itemName5;
    private javax.swing.JScrollPane itemName6;
    private javax.swing.JScrollPane itemName7;
    private javax.swing.JScrollPane itemName8;
    private javax.swing.JScrollPane itemName9;
    private javax.swing.JTextArea itemNameTextArea1;
    private javax.swing.JTextArea itemNameTextArea2;
    private javax.swing.JTextArea itemNameTextArea3;
    private javax.swing.JTextArea itemNameTextArea4;
    private javax.swing.JTextArea itemNameTextArea5;
    private javax.swing.JTextArea itemNameTextArea6;
    private javax.swing.JTextArea itemNameTextArea7;
    private javax.swing.JTextArea itemNameTextArea8;
    private javax.swing.JTextArea itemNameTextArea9;
    private javax.swing.JLabel itemPicture1;
    private javax.swing.JLabel itemPicture2;
    private javax.swing.JLabel itemPicture3;
    private javax.swing.JLabel itemPicture4;
    private javax.swing.JLabel itemPicture5;
    private javax.swing.JLabel itemPicture6;
    private javax.swing.JLabel itemPicture7;
    private javax.swing.JLabel itemPicture8;
    private javax.swing.JLabel itemPicture9;
    private javax.swing.JLabel itemPrice1;
    private javax.swing.JLabel itemPrice2;
    private javax.swing.JLabel itemPrice3;
    private javax.swing.JLabel itemPrice4;
    private javax.swing.JLabel itemPrice5;
    private javax.swing.JLabel itemPrice6;
    private javax.swing.JLabel itemPrice7;
    private javax.swing.JLabel itemPrice8;
    private javax.swing.JLabel itemPrice9;
    private javax.swing.JLabel itemQuantity1;
    private javax.swing.JLabel itemQuantity2;
    private javax.swing.JLabel itemQuantity3;
    private javax.swing.JLabel itemQuantity4;
    private javax.swing.JLabel itemQuantity5;
    private javax.swing.JLabel itemQuantity6;
    private javax.swing.JLabel itemQuantity7;
    private javax.swing.JLabel itemQuantity8;
    private javax.swing.JLabel itemQuantity9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel priceLbl1;
    private javax.swing.JLabel priceLbl2;
    private javax.swing.JLabel priceLbl3;
    private javax.swing.JLabel priceLbl4;
    private javax.swing.JLabel priceLbl5;
    private javax.swing.JLabel priceLbl6;
    private javax.swing.JLabel priceLbl7;
    private javax.swing.JLabel priceLbl8;
    private javax.swing.JLabel priceLbl9;
    // End of variables declaration//GEN-END:variables
}
