/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author rogercanayon
 */
public class VendingMachineSlot extends javax.swing.JPanel {

    /**
     * Creates new form VendingMachineSlot
     */
    public VendingMachineSlot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        SlotContainer = new javax.swing.JPanel();
        Slot1 = new javax.swing.JPanel();
        Slot2 = new javax.swing.JPanel();
        Slot3 = new javax.swing.JPanel();
        Slot4 = new javax.swing.JPanel();
        Slot5 = new javax.swing.JPanel();
        Slot6 = new javax.swing.JPanel();
        Slot7 = new javax.swing.JPanel();
        Slot8 = new javax.swing.JPanel();
        Slot9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 2, 0, 2));

        SlotContainer.setBackground(new java.awt.Color(153, 153, 153));
        SlotContainer.setLayout(new java.awt.GridLayout(3, 3, 2, 2));

        javax.swing.GroupLayout Slot1Layout = new javax.swing.GroupLayout(Slot1);
        Slot1.setLayout(Slot1Layout);
        Slot1Layout.setHorizontalGroup(
            Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot1Layout.setVerticalGroup(
            Slot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot1);

        javax.swing.GroupLayout Slot2Layout = new javax.swing.GroupLayout(Slot2);
        Slot2.setLayout(Slot2Layout);
        Slot2Layout.setHorizontalGroup(
            Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot2Layout.setVerticalGroup(
            Slot2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot2);

        javax.swing.GroupLayout Slot3Layout = new javax.swing.GroupLayout(Slot3);
        Slot3.setLayout(Slot3Layout);
        Slot3Layout.setHorizontalGroup(
            Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot3Layout.setVerticalGroup(
            Slot3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot3);

        javax.swing.GroupLayout Slot4Layout = new javax.swing.GroupLayout(Slot4);
        Slot4.setLayout(Slot4Layout);
        Slot4Layout.setHorizontalGroup(
            Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot4Layout.setVerticalGroup(
            Slot4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot4);

        javax.swing.GroupLayout Slot5Layout = new javax.swing.GroupLayout(Slot5);
        Slot5.setLayout(Slot5Layout);
        Slot5Layout.setHorizontalGroup(
            Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot5Layout.setVerticalGroup(
            Slot5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot5);

        javax.swing.GroupLayout Slot6Layout = new javax.swing.GroupLayout(Slot6);
        Slot6.setLayout(Slot6Layout);
        Slot6Layout.setHorizontalGroup(
            Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot6Layout.setVerticalGroup(
            Slot6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot6);

        javax.swing.GroupLayout Slot7Layout = new javax.swing.GroupLayout(Slot7);
        Slot7.setLayout(Slot7Layout);
        Slot7Layout.setHorizontalGroup(
            Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot7Layout.setVerticalGroup(
            Slot7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot7);

        javax.swing.GroupLayout Slot8Layout = new javax.swing.GroupLayout(Slot8);
        Slot8.setLayout(Slot8Layout);
        Slot8Layout.setHorizontalGroup(
            Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot8Layout.setVerticalGroup(
            Slot8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot8);

        javax.swing.GroupLayout Slot9Layout = new javax.swing.GroupLayout(Slot9);
        Slot9.setLayout(Slot9Layout);
        Slot9Layout.setHorizontalGroup(
            Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 119, Short.MAX_VALUE)
        );
        Slot9Layout.setVerticalGroup(
            Slot9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        SlotContainer.add(Slot9);

        jPanel3.setBackground(new java.awt.Color(51, 0, 51));
        jPanel3.setForeground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 247, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(SlotContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SlotContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Slot1;
    private javax.swing.JPanel Slot2;
    private javax.swing.JPanel Slot3;
    private javax.swing.JPanel Slot4;
    private javax.swing.JPanel Slot5;
    private javax.swing.JPanel Slot6;
    private javax.swing.JPanel Slot7;
    private javax.swing.JPanel Slot8;
    private javax.swing.JPanel Slot9;
    private javax.swing.JPanel SlotContainer;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
