/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.awt.event.ActionListener;

/**
 *
 * @author rogercanayon
 */
public class ChangePrice extends javax.swing.JFrame {

    /**
     * Creates new form RestockProduct
     */
    public ChangePrice() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl = new javax.swing.JLabel();
        ChangeBtn = new javax.swing.JButton();
        ItemName = new javax.swing.JLabel();
        newPrice = new javax.swing.JTextField();
        WarningLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vending Machine Factory");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(85, 88, 95));

        Lbl.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Lbl.setForeground(new java.awt.Color(255, 255, 255));
        Lbl.setText("Change Price");

        ChangeBtn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ChangeBtn.setText("Change");

        ItemName.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ItemName.setForeground(new java.awt.Color(255, 255, 255));
        ItemName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName.setText("ItemName");

        newPrice.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        WarningLbl.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        WarningLbl.setForeground(new java.awt.Color(255, 255, 255));
        WarningLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WarningLbl.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 68, Short.MAX_VALUE)
                .addComponent(Lbl)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(ChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(WarningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(newPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Lbl)
                .addGap(18, 18, 18)
                .addComponent(ItemName)
                .addGap(35, 35, 35)
                .addComponent(newPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(WarningLbl)
                .addGap(18, 18, 18)
                .addComponent(ChangeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets a button action listener
     * @param actn - an action listener
     */
    public void setChangePriceBtnListener(ActionListener actn)
    {
        ChangeBtn.addActionListener(actn);
    }

    /**
     * Returns the new price entered
     * @return new price entered
     */
    public int getNewPrice()
    {
        return Integer.parseInt(newPrice.getText());
    }

    /**
     * Sets the visibility of the label
     * @param check - a boolean value
     */
    public void setWarningVisible(boolean check)
    {
        WarningLbl.setVisible(check);
    }

    /**
     * Sets the message of the label
     * @param txt - contains the text
     */
    public void setWarningMessage(String txt)
    {
        WarningLbl.setText(txt);
    }
    
    /**
     * Sets the item name
     * @param Name - contains the name
     */
    public void setItemName(String Name)
    {
        ItemName.setText(Name);
    }
    
    /**
     * Clears the text area
     */
    public void clearTA()
    {
        newPrice.setText("");
    }
    
    /**
     * Sets a button action listener
     * @param actn - an action listener
     */
    public void setDoneBtnListener(ActionListener actn)
    {
        ChangeBtn.addActionListener(actn);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestockProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestockProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeBtn;
    private javax.swing.JLabel ItemName;
    private javax.swing.JLabel Lbl;
    private javax.swing.JLabel WarningLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField newPrice;
    // End of variables declaration//GEN-END:variables
}
